workflows:
  ios-codemagic-workflow:
    name: Exploring Codemagic for iOS
    environment:
      groups:
        - appstore_credentials
    scripts:
      - name: Initialize Keychain
        script: keychain initialize
      - name: Fetch signing files
        script: app-store-connect fetch-signing-files "com.yogesh.iAmRich" --type IOS_APP_DEVELOPMENT --create
      - name: Set up signing certificate
        script: keychain add-certificates
      - name: Set up code signing on xcode project
        script: xcode-project use-profiles
      - name: Build app
        script: xcodebuild build -workspace "iAmRich.xcworkspace" -scheme "iAmRich" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - yogeshparwani99.yp@gmail.com
          - yogesh.parwani@haptik.ai
        notify:
          success: true
          failure: true
